development:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  authentication: "plain"
  user_name: "net901703@gmail.com"
  password: "huxx21"
  enable_starttls_auto: true
production:
  address: "smtp.mailgun.org"
  port: 587
  domain: "gmail.com"
  authentication: "plain"
  user_name: "net901703@gmail.com"
  password: "huxx21"
  enable_starttls_auto: true